packages:
    - "apps/*"
    - "packages/*"

catalogs:
    vue:
        vue: "3.4.31"
        pinia: "2.1.7"
        "vue-router": "4.4.0" # 修正：加引号，用横杠

    build:
        vite: "5.3.3"
        "@vitejs/plugin-vue": "5.0.4" # 修正：真实包名
        "@vitejs/plugin-vue-jsx": "4.0.1"
        typescript: "5.5.3"
        "vue-tsc": "2.0.26"
        "vite-plugin-vue-devtools": "7.3.6"
        "vite-plugin-checker": "0.7.2"
        "rollup-plugin-visualizer": "5.12.0"
        vitest: "2.0.3"

    tools:
        "@tsconfig/node20": "20.1.4" # 修正
        "@types/node": "20.14.10" # 修正
        "@vue/tsconfig": "0.5.1" # 修正
        "@types/sortablejs": "^1.15.9" # 修正

    ui:
        "@icon-park/vue-next": "1.4.2" # 修正

    utils:
        "copy-text-to-clipboard": "3.2.0" # 修正
        nanoid: "5.0.7"
        "vue-draggable-plus": "^0.6.1" # 修正

    validation:
        "vee-validate": "4.13.2" # 修正

    json:
        "vue-json-pretty": "2.4.0" # 修正

    flow:
        "@vue-flow/core": "1.39.0" # 修正
        "@vue-flow/additional-components": "1.3.3"

    table:
        "@visactor/vtable": "^0.20.0" # 修正

    sentry:
        "@sentry/vue": "8.26.0" # 修正
        "@sentry/vite-plugin": "2.22.2"

    test:
        "@vue/test-utils": "2.4.6" # 修正

    tiptap:
        "@tiptap/core": "2.5.1" # 修正
        "@tiptap/pm": "2.5.1"
        "@tiptap/starter-kit": "2.5.1"
        "@tiptap/vue-3": "2.5.1"

    echarts:
        echarts: "5.5.1"
        "vue-echarts": "6.7.3" # 修正
        zrender: "5.6.0"
